/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -t Protector11.gltf
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
    Cylinder_3: THREE.Mesh
    Cylinder_4: THREE.Mesh
    right_engine_cube: THREE.Mesh
    left_wing: THREE.Mesh
    right_wing: THREE.Mesh
    nose_cone: THREE.Mesh
    RRE_rear_top_1: THREE.Mesh
    RRE_rear_top_2: THREE.Mesh
    RRE_rear_top_3: THREE.Mesh
    RRE_rear_top_4: THREE.Mesh
    RRE_rear_top_5: THREE.Mesh
    RRE_rear_top_6: THREE.Mesh
    RRE_rear_top_7: THREE.Mesh
    RRE_rear_top_8: THREE.Mesh
    RRE_rear_bottom_1: THREE.Mesh
    RRE_rear_bottom_2: THREE.Mesh
    RRE_rear_bottom_3: THREE.Mesh
    RRE_rear_bottom_4: THREE.Mesh
    RRE_rear_bottom_5: THREE.Mesh
    RRE_rear_bottom_6: THREE.Mesh
    RRE_rear_bottom_7: THREE.Mesh
    RRE_rear_bottom_8: THREE.Mesh
    right_front_engine: THREE.Mesh
    RFE1_rear: THREE.Mesh
    RFE_front_1: THREE.Mesh
    RFE_front_2: THREE.Mesh
    RFE_front_3: THREE.Mesh
    RFE_front_4: THREE.Mesh
    RFE_front_5: THREE.Mesh
    RFE_front_7: THREE.Mesh
    RFE_front_8: THREE.Mesh
    RFE2_rear: THREE.Mesh
    RFE3_rear: THREE.Mesh
    RFE4_rear: THREE.Mesh
    RFE5_rear: THREE.Mesh
    RFE6_rear: THREE.Mesh
    RFE7_rear: THREE.Mesh
    RFE8_rear: THREE.Mesh
    left_front_engine: THREE.Mesh
    LFE1_rear001: THREE.Mesh
    LFE_front_1001: THREE.Mesh
    LFE_front_2001: THREE.Mesh
    LFE_front_3001: THREE.Mesh
    LFE_front_4001: THREE.Mesh
    LFE_front_5001: THREE.Mesh
    LFE_front_6001: THREE.Mesh
    LFE2_rear001: THREE.Mesh
    LFE3_rear001: THREE.Mesh
    LFE4_rear001: THREE.Mesh
    LFE5_rear001: THREE.Mesh
    LFE6_rear001: THREE.Mesh
    LFE7_rear001: THREE.Mesh
    LFE8_rear001: THREE.Mesh
    LFE_front_7001: THREE.Mesh
    LFE_front_8001: THREE.Mesh
    right_engine_cube001: THREE.Mesh
    LRE_rear_bottom_1: THREE.Mesh
    LRE_rear_bottom_2: THREE.Mesh
    LRE_rear_bottom_3: THREE.Mesh
    LRE_rear_bottom_4: THREE.Mesh
    LRE_rear_bottom_5: THREE.Mesh
    LRE_rear_bottom_6: THREE.Mesh
    LRE_rear_bottom_7: THREE.Mesh
    LRE_rear_bottom_8: THREE.Mesh
    LRE_rear_top_1: THREE.Mesh
    LRE_rear_top_5: THREE.Mesh
    LRE_rear_top_2: THREE.Mesh
    LRE_rear_top_3: THREE.Mesh
    LRE_rear_top_4: THREE.Mesh
    LRE_rear_top_6: THREE.Mesh
    LRE_rear_top_7: THREE.Mesh
    LRE_rear_top_8: THREE.Mesh
    tail_light: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    blue: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const suffixes: string[] = [];
  const { nodes, materials } = useGLTF(
    "src/assets/Protector11.gltf"
  ) as unknown as GLTFResult;

  const getNodeSuffix = (nodeName: string) => {
    const parts = nodeName.split(".");
    return parts[parts.length - 1];
  };

  const logPartNames = () => {
    let i = 0
    Object.keys(nodes).forEach((nodeName) => {
      const suffix = getNodeSuffix(nodeName);
      suffixes.push(suffix); // Push the suffix to the globally available array
      console.log("numeric", i, "Part:", suffix); // Log the part name
      i++;
    });
  };

  // Call the function to log part names
  logPartNames();
  
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.01, 0, 0.05]}
        rotation={[Math.PI / 2, -1.57, 0]}
        scale={[0.27, 2.42, 0.27]}
      >
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.001"]}
        />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.blue} />
        <mesh
          geometry={nodes.Cylinder_2.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cylinder_3.geometry}
          material={materials["blue"]}
        />
        <mesh
          geometry={nodes.Cylinder_4.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <mesh
        geometry={nodes.right_engine_cube.geometry}
        material={materials["Material.001"]}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        geometry={nodes.left_wing.geometry}
        material={materials["Material.001"]}
        position={[-0.98, -0.11, 0.06]}
        rotation={[0.18, 1.57, 0]}
        scale={[-0.5, -0.11, -0.33]}
      />
      <mesh
        geometry={nodes.right_wing.geometry}
        material={materials["Material.001"]}
        position={[0.98, -0.01, 0.1]}
        rotation={[-2.96, -Math.PI / 2, 0]}
        scale={[-0.5, -0.11, -0.33]}
      />
      <mesh
        geometry={nodes.nose_cone.geometry}
        material={nodes.nose_cone.material}
        position={[-0.01, 0.02, -1.65]}
        rotation={[-Math.PI / 2, -1.57, 0]}
        scale={[0.37, 0.7, 0.21]}
      />
      <mesh
        name={suffixes[12]}
        geometry={nodes.RRE_rear_top_1.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />

      <mesh
        name={suffixes[13]}
        geometry={nodes.RRE_rear_top_2.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[14]}
        geometry={nodes.RRE_rear_top_3.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[15]}
        geometry={nodes.RRE_rear_top_4.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[16]}
        geometry={nodes.RRE_rear_top_5.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[17]}
        geometry={nodes.RRE_rear_top_6.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[18]}
        geometry={nodes.RRE_rear_top_7.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[19]}
        geometry={nodes.RRE_rear_top_8.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[20]}
        geometry={nodes.RRE_rear_bottom_1.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[21]}
        geometry={nodes.RRE_rear_bottom_2.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[22]}
        geometry={nodes.RRE_rear_bottom_3.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[23]}
        geometry={nodes.RRE_rear_bottom_4.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[24]}
        geometry={nodes.RRE_rear_bottom_5.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[25]}
        geometry={nodes.RRE_rear_bottom_6.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[26]}
        geometry={nodes.RRE_rear_bottom_7.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[27]}
        geometry={nodes.RRE_rear_bottom_8.geometry}
        material={materials.Black}
        position={[0.85, -0.38, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[28]}
        geometry={nodes.right_front_engine.geometry}
        material={materials["Material.001"]}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[29]}
        geometry={nodes.RFE1_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[30]}
        geometry={nodes.RFE_front_1.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[31]}
        geometry={nodes.RFE_front_2.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[32]}
        geometry={nodes.RFE_front_3.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[33]}
        geometry={nodes.RFE_front_4.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[34]}
        geometry={nodes.RFE_front_5.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[35]}
        geometry={nodes.RFE_front_7.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[36]}
        geometry={nodes.RFE_front_8.geometry}
        material={materials.Black}
        position={[0.7, 0.05, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[37]}
        geometry={nodes.RFE2_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[38]}
        geometry={nodes.RFE3_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[39]}
        geometry={nodes.RFE4_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[40]}
        geometry={nodes.RFE5_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[41]}
        geometry={nodes.RFE6_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[42]}
        geometry={nodes.RFE7_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[43]}
        geometry={nodes.RFE8_rear.geometry}
        material={materials.Black}
        position={[0.7, -0.13, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[44]}
        geometry={nodes.left_front_engine.geometry}
        material={materials["Material.001"]}
        position={[-0.7, 0.05, 0.2]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[45]}
        geometry={nodes.LFE1_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[46]}
        geometry={nodes.LFE_front_1001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[47]}
        geometry={nodes.LFE_front_2001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[48]}
        geometry={nodes.LFE_front_3001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[49]}
        geometry={nodes.LFE_front_4001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[50]}
        geometry={nodes.LFE_front_5001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[51]}
        geometry={nodes.LFE_front_6001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[52]}
        geometry={nodes.LFE2_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[53]}
        geometry={nodes.LFE3_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[54]}
        geometry={nodes.LFE4_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[55]}
        geometry={nodes.LFE5_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[56]}
        geometry={nodes.LFE6_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[57]}
        geometry={nodes.LFE7_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[58]}
        geometry={nodes.LFE8_rear001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[59]}
        geometry={nodes.LFE_front_7001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[60]}
        geometry={nodes.LFE_front_8001.geometry}
        material={materials.Black}
        position={[-0.7, 0.05, 0.21]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        name={suffixes[61]}
        geometry={nodes.right_engine_cube001.geometry}
        material={materials["Material.001"]}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[62]}
        geometry={nodes.LRE_rear_bottom_1.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[63]}
        geometry={nodes.LRE_rear_bottom_2.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[64]}
        geometry={nodes.LRE_rear_bottom_3.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[65]}
        geometry={nodes.LRE_rear_bottom_4.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[66]}
        geometry={nodes.LRE_rear_bottom_5.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[67]}
        geometry={nodes.LRE_rear_bottom_6.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[68]}
        geometry={nodes.LRE_rear_bottom_7.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[69]}
        geometry={nodes.LRE_rear_bottom_8.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[70]}
        geometry={nodes.LRE_rear_top_1.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[71]}
        geometry={nodes.LRE_rear_top_2.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[72]}
        geometry={nodes.LRE_rear_top_3.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[73]}
        geometry={nodes.LRE_rear_top_4.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[74]}
        geometry={nodes.LRE_rear_top_5.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[75]}
        geometry={nodes.LRE_rear_top_6.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[76]}
        geometry={nodes.LRE_rear_top_7.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[77]}
        geometry={nodes.LRE_rear_top_8.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        name={suffixes[78]}
        geometry={nodes.tail_light.geometry}
        material={materials.Black}
        position={[-0.86, -0.36, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
    </group>
  );
}

useGLTF.preload("src/assets/Protector11.gltf");
