/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 -t Protector10.gltf
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh;
    Cylinder_1: THREE.Mesh;
    Cylinder_2: THREE.Mesh;
    left_engine_cube: THREE.Mesh;
    right_engine_cube: THREE.Mesh;
    left_rear_engine_light_two: THREE.Mesh;
    left_rear_engine_light_one: THREE.Mesh;
    left_rear_engine_light_three: THREE.Mesh;
    left_rear_engine_light_four: THREE.Mesh;
    left_front_engine: THREE.Mesh;
    right_front_engine: THREE.Mesh;
    left_wing: THREE.Mesh;
    right_wing: THREE.Mesh;
    left_front_engine_light_1: THREE.Mesh;
    left_front_engine_light_2: THREE.Mesh;
    left_front_engine_light_3: THREE.Mesh;
    left_front_engine_light_4: THREE.Mesh;
    left_front_engine_light_5: THREE.Mesh;
    left_front_engine_light_6: THREE.Mesh;
    left_front_engine_light_7: THREE.Mesh;
    nose_cone: THREE.Mesh;
    left_front_engine_light_8: THREE.Mesh;
    right_front_engine_light_8: THREE.Mesh;
    right_front_engine_light_7: THREE.Mesh;
    right_front_engine_light_6: THREE.Mesh;
    right_front_engine_light_5: THREE.Mesh;
    right_front_engine_light_4: THREE.Mesh;
    right_front_engine_light_3: THREE.Mesh;
    right_front_engine_light_2: THREE.Mesh;
    right_front_engine_light_1: THREE.Mesh;
    right_rear_engine_light_two: THREE.Mesh;
    right_rear_engine_light_one: THREE.Mesh;
    right_rear_engine_light_four: THREE.Mesh;
    right_rear_engine_light_three: THREE.Mesh;
    tail_light: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
    blue: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    "src/assets/Protector10.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.13, 1.36, 0.05]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.27, 2.42, 0.27]}
      >
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.001"]}
        />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.blue} />
        <mesh
          geometry={nodes.Cylinder_2.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        geometry={nodes.left_engine_cube.geometry}
        material={materials["Material.001"]}
        position={[-0.71, 0.96, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        geometry={nodes.right_engine_cube.geometry}
        material={materials["Material.001"]}
        position={[0.99, 0.98, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.32, 0.32, 0.27]}
      />
      <mesh
        geometry={nodes.left_rear_engine_light_two.geometry}
        material={nodes.left_rear_engine_light_two.material}
        position={[-0.85, 0.98, 1.82]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.26, 0.24, 0.04]}
      />
      <mesh
        geometry={nodes.left_rear_engine_light_one.geometry}
        material={nodes.left_rear_engine_light_one.material}
        position={[-0.76, 0.98, 1.82]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.26, 0.24, 0.04]}
      />
      <mesh
        geometry={nodes.left_rear_engine_light_three.geometry}
        material={nodes.left_rear_engine_light_three.material}
        position={[-0.67, 0.98, 1.83]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.26, 0.24, 0.04]}
      />
      <mesh
        geometry={nodes.left_rear_engine_light_four.geometry}
        material={nodes.left_rear_engine_light_four.material}
        position={[-0.58, 0.98, 1.81]}
        rotation={[0.94, -Math.PI / 2, 0]}
        scale={[0.26, 0.24, 0.04]}
      />
      <mesh
        geometry={nodes.left_front_engine.geometry}
        material={materials["Material.001"]}
        position={[-0.57, 1.41, 0.24]}
        rotation={[0.09, -Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        geometry={nodes.right_front_engine.geometry}
        material={materials["Material.001"]}
        position={[0.83, 1.41, -0.06]}
        rotation={[-0.09, Math.PI / 2, 0]}
        scale={[1.21, 0.36, 0.73]}
      />
      <mesh
        geometry={nodes.left_wing.geometry}
        material={materials["Material.001"]}
        position={[-0.84, 1.25, 0.1]}
        rotation={[0.18, Math.PI / 2, 0]}
        scale={[-0.5, -0.11, -0.33]}
      />
      <mesh
        geometry={nodes.right_wing.geometry}
        material={materials["Material.001"]}
        position={[1.11, 1.35, 0.1]}
        rotation={[-2.96, -Math.PI / 2, 0]}
        scale={[-0.5, -0.11, -0.33]}
      />
      <mesh
        geometry={nodes.left_front_engine_light_1.geometry}
        material={materials["Material.003"]}
        position={[-0.74, 1.28, 0.09]}
        rotation={[Math.PI / 2, -1.37, Math.PI / 2]}
        scale={[0.36, 0.09, 0.25]}
      />
      <mesh
        geometry={nodes.left_front_engine_light_2.geometry}
        material={materials["Material.003"]}
        position={[-0.87, 1.32, 0.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.33, 0.08, 0.32]}
      />
      <mesh
        geometry={nodes.left_front_engine_light_3.geometry}
        material={materials["Material.003"]}
        position={[-0.95, 1.32, 0.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.35, 0.08, 0.34]}
      />
      <mesh
        geometry={nodes.left_front_engine_light_4.geometry}
        material={materials["Material.003"]}
        position={[-1.01, 1.31, 0.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.33, 0.09, 0.32]}
      />
      <mesh
        geometry={nodes.left_front_engine_light_5.geometry}
        material={materials["Material.003"]}
        position={[-1.1, 1.3, 0.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.33, 0.1, 0.34]}
      />
      <mesh
        geometry={nodes.left_front_engine_light_6.geometry}
        material={materials["Material.003"]}
        position={[-1.17, 1.3, 0.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.33, 0.09, 0.34]}
      />
      <mesh
        geometry={nodes.left_front_engine_light_7.geometry}
        material={materials["Material.003"]}
        position={[-1.24, 1.3, 0.09]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.33, 0.09, 0.34]}
      />
      <mesh
        geometry={nodes.nose_cone.geometry}
        material={nodes.nose_cone.material}
        position={[0.13, 1.38, -1.65]}
        rotation={[-Math.PI / 2, -1.57, 0]}
        scale={[0.37, 0.7, 0.21]}
      />
      <mesh
        geometry={nodes.left_front_engine_light_8.geometry}
        material={materials["Material.003"]}
        position={[-1.03, 1.29, 0.1]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.3, 0.1, 0.04]}
      />
      <mesh
        geometry={nodes.right_front_engine_light_8.geometry}
        material={materials["Material.003"]}
        position={[1.32, 1.3, 0.09]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.36, -0.09, -0.02]}
      />
      <mesh
        geometry={nodes.right_front_engine_light_7.geometry}
        material={materials["Material.003"]}
        position={[1.25, 1.31, 0.07]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.36, -0.09, -0.02]}
      />
      <mesh
        geometry={nodes.right_front_engine_light_6.geometry}
        material={materials["Material.003"]}
        position={[1.17, 1.32, 0.09]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.36, -0.09, -0.02]}
      />
      <mesh
        geometry={nodes.right_front_engine_light_5.geometry}
        material={materials["Material.003"]}
        position={[1.1, 1.32, 0.09]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.36, -0.08, -0.02]}
      />
      <mesh
        geometry={nodes.right_front_engine_light_4.geometry}
        material={materials["Material.003"]}
        position={[1.03, 1.33, 0.09]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.36, -0.08, -0.02]}
      />
      <mesh
        geometry={nodes.right_front_engine_light_3.geometry}
        material={materials["Material.003"]}
        position={[0.96, 1.33, 0.09]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.32, -0.07, -0.02]}
      />
      <mesh
        geometry={nodes.right_front_engine_light_2.geometry}
        material={materials["Material.003"]}
        position={[0.89, 1.33, 0.09]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.32, -0.07, -0.02]}
      />
      <mesh
        geometry={nodes.right_front_engine_light_1.geometry}
        material={materials["Material.003"]}
        position={[0.83, 1.34, 0.09]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[-0.32, -0.07, -0.02]}
      />
      <mesh
        geometry={nodes.right_rear_engine_light_two.geometry}
        material={nodes.right_rear_engine_light_two.material}
        position={[0.85, 0.97, 1.8]}
        rotation={[-0.18, -1.56, -0.89]}
        scale={[0.29, 0.19, 0.05]}
      />
      <mesh
        geometry={nodes.right_rear_engine_light_one.geometry}
        material={nodes.right_rear_engine_light_one.material}
        position={[0.95, 0.97, 1.77]}
        rotation={[-0.18, -1.56, -0.89]}
        scale={[0.29, 0.19, 0.05]}
      />
      <mesh
        geometry={nodes.right_rear_engine_light_four.geometry}
        material={nodes.right_rear_engine_light_four.material}
        position={[1.04, 0.97, 1.76]}
        rotation={[-0.18, -1.56, -0.89]}
        scale={[0.29, 0.19, 0.05]}
      />
      <mesh
        geometry={nodes.right_rear_engine_light_three.geometry}
        material={nodes.right_rear_engine_light_three.material}
        position={[1.14, 0.97, 1.76]}
        rotation={[-0.18, -1.56, -0.89]}
        scale={[0.29, 0.19, 0.05]}
      />
      <mesh
        name="tail_light"
        geometry={nodes.tail_light.geometry}
        material={materials.Material}
        position={[-0.01, 0, 0.05]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.27, 2.42, 0.27]}
      />
    </group>
  );
}

useGLTF.preload("src/assets/Protector10.glb");
